//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputActions/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""35658d1c-aa36-455f-b894-70d024405f44"",
            ""actions"": [
                {
                    ""name"": ""MoveP1"",
                    ""type"": ""Value"",
                    ""id"": ""e71779b3-a0d2-4ea3-b728-79fdf1576090"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectP1"",
                    ""type"": ""Button"",
                    ""id"": ""bd348b23-fa8a-4c68-8662-7aa26a53cc2c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SkipP1"",
                    ""type"": ""Button"",
                    ""id"": ""e77cad75-d8fe-4e90-9e8c-ecc25f241f45"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PauseP1"",
                    ""type"": ""Button"",
                    ""id"": ""31b06005-7e68-46cd-9285-dc5125e4220e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveP2"",
                    ""type"": ""Value"",
                    ""id"": ""c16f23b8-f851-4257-a761-238a4c8eace7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectP2"",
                    ""type"": ""Button"",
                    ""id"": ""8a3ba8ca-627c-4971-b8b7-b7c2a7f784fd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SkipP2"",
                    ""type"": ""Button"",
                    ""id"": ""01ad08ce-9427-40b6-b423-20b0f0dce9f3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PauseP2"",
                    ""type"": ""Button"",
                    ""id"": ""89e9e68c-5fec-4ac7-9b09-f52a371081fa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""146cdba7-b566-4069-b2e6-32a9f1782754"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""71d07bfc-d623-4336-ae8a-0aee44400346"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""38f828d4-4a1f-4e51-b239-7e9b23fb8458"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c0994c2a-4d4d-453c-abf8-afd715ca6805"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""caa52433-f027-48c3-905b-d44e6920a378"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2bf57fbf-d60d-405f-a2bf-f546a9077176"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""016dcf5e-2076-4473-a708-4c2993cefa0e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0526d904-d907-4133-8071-7ea98b6b3172"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a176b365-ebb3-4535-953c-6e353cff904c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""271e63a1-1651-4b3f-829b-d5dd0b6f0aee"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a1c5a36-15a9-404e-932a-635a798d90d6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8df83a4f-c689-4699-9a02-167b1f4aaef6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""076f3d31-1a16-4d8b-b071-a62d339523ed"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3a20665e-f7b9-43d2-a53f-cee03aaa92e4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a4e2ad20-5753-4f4d-95a0-639cc8872aae"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""84b67e67-320f-4ce7-82a8-11bec187c56e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bce8d933-963f-4400-ae2f-88525539e2fd"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cda100f7-ff85-429a-bb21-08a896f465b2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddcc697a-97b2-4b8c-a457-d434dbadf5f9"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a024b2d9-2b33-4fd8-be1f-4f53540c12fd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ca604a-08be-413c-8b6a-8305e8ddcee7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7897c876-56c7-4d4d-9c54-4c9d8261aba7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""864daf92-f3df-4cc1-81c3-621076cc6fce"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f3e5bdc-518a-49b3-a881-78aa3338770d"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0c850d3-13b4-4709-bc0e-f5c4d30eb76b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac7fa281-f059-480d-9f0e-dd576b4e3291"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_MoveP1 = m_Gameplay.FindAction("MoveP1", throwIfNotFound: true);
        m_Gameplay_SelectP1 = m_Gameplay.FindAction("SelectP1", throwIfNotFound: true);
        m_Gameplay_SkipP1 = m_Gameplay.FindAction("SkipP1", throwIfNotFound: true);
        m_Gameplay_PauseP1 = m_Gameplay.FindAction("PauseP1", throwIfNotFound: true);
        m_Gameplay_MoveP2 = m_Gameplay.FindAction("MoveP2", throwIfNotFound: true);
        m_Gameplay_SelectP2 = m_Gameplay.FindAction("SelectP2", throwIfNotFound: true);
        m_Gameplay_SkipP2 = m_Gameplay.FindAction("SkipP2", throwIfNotFound: true);
        m_Gameplay_PauseP2 = m_Gameplay.FindAction("PauseP2", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, GameInputActions.Gameplay.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_MoveP1;
    private readonly InputAction m_Gameplay_SelectP1;
    private readonly InputAction m_Gameplay_SkipP1;
    private readonly InputAction m_Gameplay_PauseP1;
    private readonly InputAction m_Gameplay_MoveP2;
    private readonly InputAction m_Gameplay_SelectP2;
    private readonly InputAction m_Gameplay_SkipP2;
    private readonly InputAction m_Gameplay_PauseP2;
    public struct GameplayActions
    {
        private @GameInputActions m_Wrapper;
        public GameplayActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveP1 => m_Wrapper.m_Gameplay_MoveP1;
        public InputAction @SelectP1 => m_Wrapper.m_Gameplay_SelectP1;
        public InputAction @SkipP1 => m_Wrapper.m_Gameplay_SkipP1;
        public InputAction @PauseP1 => m_Wrapper.m_Gameplay_PauseP1;
        public InputAction @MoveP2 => m_Wrapper.m_Gameplay_MoveP2;
        public InputAction @SelectP2 => m_Wrapper.m_Gameplay_SelectP2;
        public InputAction @SkipP2 => m_Wrapper.m_Gameplay_SkipP2;
        public InputAction @PauseP2 => m_Wrapper.m_Gameplay_PauseP2;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @MoveP1.started += instance.OnMoveP1;
            @MoveP1.performed += instance.OnMoveP1;
            @MoveP1.canceled += instance.OnMoveP1;
            @SelectP1.started += instance.OnSelectP1;
            @SelectP1.performed += instance.OnSelectP1;
            @SelectP1.canceled += instance.OnSelectP1;
            @SkipP1.started += instance.OnSkipP1;
            @SkipP1.performed += instance.OnSkipP1;
            @SkipP1.canceled += instance.OnSkipP1;
            @PauseP1.started += instance.OnPauseP1;
            @PauseP1.performed += instance.OnPauseP1;
            @PauseP1.canceled += instance.OnPauseP1;
            @MoveP2.started += instance.OnMoveP2;
            @MoveP2.performed += instance.OnMoveP2;
            @MoveP2.canceled += instance.OnMoveP2;
            @SelectP2.started += instance.OnSelectP2;
            @SelectP2.performed += instance.OnSelectP2;
            @SelectP2.canceled += instance.OnSelectP2;
            @SkipP2.started += instance.OnSkipP2;
            @SkipP2.performed += instance.OnSkipP2;
            @SkipP2.canceled += instance.OnSkipP2;
            @PauseP2.started += instance.OnPauseP2;
            @PauseP2.performed += instance.OnPauseP2;
            @PauseP2.canceled += instance.OnPauseP2;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @MoveP1.started -= instance.OnMoveP1;
            @MoveP1.performed -= instance.OnMoveP1;
            @MoveP1.canceled -= instance.OnMoveP1;
            @SelectP1.started -= instance.OnSelectP1;
            @SelectP1.performed -= instance.OnSelectP1;
            @SelectP1.canceled -= instance.OnSelectP1;
            @SkipP1.started -= instance.OnSkipP1;
            @SkipP1.performed -= instance.OnSkipP1;
            @SkipP1.canceled -= instance.OnSkipP1;
            @PauseP1.started -= instance.OnPauseP1;
            @PauseP1.performed -= instance.OnPauseP1;
            @PauseP1.canceled -= instance.OnPauseP1;
            @MoveP2.started -= instance.OnMoveP2;
            @MoveP2.performed -= instance.OnMoveP2;
            @MoveP2.canceled -= instance.OnMoveP2;
            @SelectP2.started -= instance.OnSelectP2;
            @SelectP2.performed -= instance.OnSelectP2;
            @SelectP2.canceled -= instance.OnSelectP2;
            @SkipP2.started -= instance.OnSkipP2;
            @SkipP2.performed -= instance.OnSkipP2;
            @SkipP2.canceled -= instance.OnSkipP2;
            @PauseP2.started -= instance.OnPauseP2;
            @PauseP2.performed -= instance.OnPauseP2;
            @PauseP2.canceled -= instance.OnPauseP2;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMoveP1(InputAction.CallbackContext context);
        void OnSelectP1(InputAction.CallbackContext context);
        void OnSkipP1(InputAction.CallbackContext context);
        void OnPauseP1(InputAction.CallbackContext context);
        void OnMoveP2(InputAction.CallbackContext context);
        void OnSelectP2(InputAction.CallbackContext context);
        void OnSkipP2(InputAction.CallbackContext context);
        void OnPauseP2(InputAction.CallbackContext context);
    }
}
